# Analog Reader Controls for Home Assistant
# Exposes analog_reader parameters for runtime configuration

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          ESP_LOGD("analog_controls", "Attempting to sync controls for ID: ${id_prefix}_analog_reader");
          if (id(${id_prefix}_analog_reader) != nullptr) {
            ESP_LOGD("analog_controls", "Analog Reader found. Syncing config...");
            // Sync Update Interval
            float interval = id(${id_prefix}_analog_update_interval).state;
            if (!isnan(interval) && interval > 0) {
               id(${id_prefix}_analog_reader)->set_update_interval((uint32_t)(interval * 1000));
            }
            // Sync Contrast
            float contrast = id(${id_prefix}_analog_contrast).state;
            if (!isnan(contrast)) {
               id(${id_prefix}_analog_reader)->set_all_contrast(contrast);
            }

            // Sync Auto Contrast
            bool auto_contrast = id(${id_prefix}_analog_auto_contrast).state;
            id(${id_prefix}_analog_reader)->set_all_auto_contrast(auto_contrast);
          } else {
             ESP_LOGE("analog_controls", "Analog Reader component NOT found with ID: ${id_prefix}_analog_reader");
          }

switch:
  # Pause Analog Processing
  - platform: template
    name: "Pause Analog Processing"
    id: ${id_prefix}_pause_analog_processing
    icon: "mdi:pause"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            id(${id_prefix}_analog_reader)->set_pause_processing(true);
          }
    turn_off_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            id(${id_prefix}_analog_reader)->set_pause_processing(false);
          }

  # Auto Contrast (Min-Max Normalization)
  - platform: template
    name: "Analog Auto Contrast"
    id: ${id_prefix}_analog_auto_contrast
    icon: "mdi:contrast-box"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            id(${id_prefix}_analog_reader)->set_all_auto_contrast(true);
          }
    turn_off_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            id(${id_prefix}_analog_reader)->set_all_auto_contrast(false);
          }

number:
  # Update Interval
  - platform: template
    name: "Analog Update Interval"
    id: ${id_prefix}_analog_update_interval
    icon: "mdi:timer"
    unit_of_measurement: "s"
    min_value: 1
    max_value: 3600
    step: 1
    initial_value: 60
    entity_category: config
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            ESP_LOGD("analog_controls", "Setting update interval to %f s", x);
            id(${id_prefix}_analog_reader)->set_update_interval((uint32_t)(x * 1000));
          } else {
            ESP_LOGE("analog_controls", "Cannot set interval: Analog Reader ID not found");
          }

  # Contrast Adjustment
  - platform: template
    name: "Analog Contrast"
    id: ${id_prefix}_analog_contrast
    icon: "mdi:contrast-circle"
    min_value: 0.1
    max_value: 5.0
    step: 0.1
    initial_value: 1.0
    entity_category: config
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          if (id(${id_prefix}_analog_reader) != nullptr) {
            id(${id_prefix}_analog_reader)->set_all_contrast(x);
          }
