# Analog Reader Controls for Home Assistant
# Exposes analog_reader parameters for runtime configuration

# Sync on_boot removed to match meter_reader_tflite behavior
# Controls will start with their initial/restored values but won't force-update the component 
# until the user interacts with their controls.
# 
# Requires substitutions:
#   id_prefix: prefix for entity IDs (e.g. "hotwater")
#   analog_reader_id: ID of the analog_reader component (default: ${id_prefix}_analog_reader)

substitutions:
  analog_reader_id: ${id_prefix}_analog_reader

switch:
  # Pause Analog Processing
  - platform: template
    name: "Pause Analog Processing"
    id: ${id_prefix}_pause_analog_processing
    icon: "mdi:pause"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_pause_processing(true);
          }
    turn_off_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_pause_processing(false);
          }

  # Auto Contrast (Min-Max Normalization)
  - platform: template
    name: "Analog Auto Contrast"
    id: ${id_prefix}_analog_auto_contrast
    icon: "mdi:auto-fix"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_all_auto_contrast(true);
          }
    turn_off_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_all_auto_contrast(false);
          }

  # Debug Visualization
  - platform: template
    name: "Analog Debug Mode"
    id: ${id_prefix}_analog_debug
    icon: "mdi:bug"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_debug(true);
          }
    turn_off_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_debug(false);
          }

number:
  # Analog Update Interval
  - platform: template
    name: "Analog Update Interval"
    id: ${id_prefix}_analog_update_interval
    icon: "mdi:timer"
    min_value: 1
    max_value: 300
    step: 1
    unit_of_measurement: "s"
    mode: box
    initial_value: 60
    entity_category: config
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_update_interval((uint32_t)(x * 1000));
          }

  # Analog Contrast
  - platform: template
    name: "Analog Contrast"
    id: ${id_prefix}_analog_contrast
    icon: "mdi:contrast-circle"
    min_value: 0.1
    max_value: 5.0
    step: 0.1
    initial_value: 1.0
    entity_category: config
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            id(${analog_reader_id})->set_all_contrast(x);
          }

select:
  # Algorithm Selection
  - platform: template
    name: "Analog Detection Algorithm"
    id: ${id_prefix}_analog_algorithm
    icon: "mdi:algorithm"
    entity_category: config
    optimistic: true
    restore_value: true
    options:
      - "legacy"
      - "radial_profile"
      - "hough_transform"
      - "template_match"
      - "auto"
    initial_option: "legacy"
    set_action:
      - lambda: |-
          if (id(${analog_reader_id}) != nullptr) {
            std::string algo = x;
            id(${analog_reader_id})->set_all_algorithm(algo);
            ESP_LOGI("analog_controls", "Algorithm changed to: %s", algo.c_str());
          }
