### enable power_down_pin in esp32_camera.yaml, this board needs it

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: ${esphome_min_version}
  name_add_mac_suffix: False
  on_boot:
    priority: 999.0
    then:
      - delay: 500ms
  project:
    name: "nliaudat.meter-reader"
    version: "${revision}.dev"
  platformio_options:
    board_build.f_cpu: 240000000L
    board_build.f_flash: 40000000L
    # board_build.partitions: huge_app.csv
    board_name: AiThinker ESP32-CAM
    board_build.extra_flags: 
    - -DBOARD_HAS_PSRAM 
    - -DTF_LITE_STATIC_MEMORY # for tflite micro
    - -DTF_LITE_DISABLE_X86_NEON #for tflite micro
    - -DESP_NN  #use hardware acceleration : https://github.com/espressif/esp-nn (only if using tflite)

substitutions:
  board: esp32cam
  framework: esp-idf

  # Camera Pins
  external_clock_pin: GPIO0
  external_clock_frequency: 20MHz
  i2c_pins_sda: GPIO26
  i2c_pins_scl: GPIO27
  data_pins:
    - GPIO5   # CAM_D0
    - GPIO18  # CAM_D1
    - GPIO19  # CAM_D2
    - GPIO21  # CAM_D3
    - GPIO36  # CAM_D4
    - GPIO39  # CAM_D5
    - GPIO34  # CAM_D6
    - GPIO35  # CAM_D7
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  
  # Power Down / Reset
  camera_pwdn_pin: GPIO32
  camera_reset_pin: "-1"

  # LED Pins
  status_led_pin: GPIO33
  flash_led_pin: GPIO4

esp32:
  board: ${board}
  flash_size: 4MB
  cpu_frequency: 240MHZ
  framework:
    type: ${framework}
    version: recommended
    sdkconfig_options:
      # CONFIG_ESP32_SPIRAM_SUPPORT: y
      # CONFIG_ESP32_SPIRAM_SPEED_40M: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      # CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      CONFIG_FATFS_LFN_STACK: "y" # to support long file name in sdcard
      CONFIG_TASK_WDT: "y" # prevents watchdog timeouts
      CONFIG_TASK_WDT_TIMEOUT_S: "30" # prevents watchdog timeouts
      CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0: "n" # prevents watchdog timeouts
      ### needed by new jpeg camera : https://github.com/esphome/esphome/pull/9496
      CONFIG_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM_USE_CAPS_ALLOC: y
      CONFIG_SPIRAM_USE_MALLOC: y
      CONFIG_LOG_DEFAULT_LEVEL: "0" # prevents "ESP-IDF" Guru Meditation Error
      CONFIG_CAMERA_TASK_STACK_SIZE: "4096"
      #### testing 
      # CONFIG_ESP32_DEFAULT_CPU_FREQ_240: y
      CONFIG_FREERTOS_HZ: "1000"


psram:

light:
  - platform: binary
    output: ${id_prefix}_flash_light_output
    name: "${name} Flash Light"
    id: ${id_prefix}_flash
  - platform: binary
    output: ${id_prefix}_status_led_output
    name: "${name} Status LED"
    id: ${id_prefix}_light

output:
  - platform: gpio
    pin: ${flash_led_pin}
    id: ${id_prefix}_flash_light_output
  - platform: gpio
    pin: ${status_led_pin}
    id: ${id_prefix}_status_led_output
    inverted: true
