esphome:
  name: host-test
  build_path: .esphome/build/host_test


host:
  mac_address: "02:00:00:00:00:00"

external_components:
  - source: components
    components: [ meter_reader_tflite, tflite_micro_helper ]

logger:

# Mock sensors needed for components
sensor:
  - platform: template
    name: "Mock Sensor"
    id: mock_sensor
    lambda: return 42.0;
    
  # Mock memory sensors to prevent errors if referenced
  - platform: template
    name: "Mock Heap"
    id: mock_heap
    lambda: return 100000.0;

text_sensor:
  - platform: template
    name: "Mock Text"
    id: mock_text
    lambda: return std::string("Ready");

meter_reader_tflite:
  id: meter_reader
  camera_id: mock_cam 
  model: "digit_recognizer_v4_10cls_GRAY.tflite"
  debug_image: true # Required for host to have an image source
  debug: true
  
  # Link outputs
  value_sensor: mock_sensor
  inference_logs: mock_text
  
  # Disable ESP32 specific hardware 
  # (Requires code changes to respect this)

# Required by dependencies
tflite_micro_helper:
